services:
  - type: web
    name: stupid-game
    env: static
    buildCommand: ""
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
